# Generated by Django 5.1.1 on 2024-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="spelling_errors_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
