# Generated by Django 5.1.1 on 2024-09-07 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_feedback_spelling_errors_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="spelling_error",
        ),
        migrations.CreateModel(
            name="SpellingError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("word", models.TextField(blank=True, null=True)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
    ]
