# Generated by Django 5.1.1 on 2024-09-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_spelling_error_spellingerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellingerror',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_errors', to='feedback.feedback'),
        ),
    ]
