# Generated by Django 5.1.1 on 2024-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="essay",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
